### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by chpiter** [zhitom/zkweb#1]
能否提供个docker镜像，谢谢

**Comment by zhitom** [comment]
建议不错，不过目前暂没有时间做这个事情，需要您耐心等待一段时间！谢谢您的建议！
目前的发布版本，只要有Java环境就可以运行，如果紧急可以临时找一个Java镜像，并且启动一个Java容器，加入该jar包，直接运行即可。

**Comment by chpiter** [comment]
> 建议不错，不过目前暂没有时间做这个事情，需要您耐心等待一段时间！谢谢您的建议！
> 目前的发布版本，只要有Java环境就可以运行，如果紧急可以临时找一个Java镜像，并且启动一个Java容器，加入该jar包，直接运行即可。

明白了，谢谢，下午搞一个
