### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by zhaolun7** [zhitom/zkweb#2]
zkWeb从10月23日运行到现在(12月3日).
1.问题：连接数太多。
这是zk server端报的日志
> 2018-12-03 11:39:11,946 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@188] - Too many connections from /10.233.233.233 - max is 60
![image](https://user-images.githubusercontent.com/16096787/49355124-12f6eb00-f701-11e8-92da-a2f37e6df697.png)

这是zkWeb端的报错
> [2018-12-03 12:09:14 WARN  http-nio-8099-exec-1-SendThread(10.233.233.233:2181)  ClientCnxn.java:1167] org.apache.zookeeper.ClientCnxn --> Session 0x0 for server 10.233.233.233/10.233.233.233:2181, unexpected error, closing socket connection and attempting reconnect
> java.io.IOException: Connection reset by peer
> 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
> 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
> 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
> 	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
> 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
> 	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
> 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
> 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1144)

**在这个测试机上运行java的其他程序连接这个zk会超时，连接其他zk集群不受影响**
我看了源码
ZkManagerImpl.create().connect(String host, int timeout)这个调用，每次调用创建一个ZooKeeper对象，且没有地方调用disconnect，因此一直占用着连接。
我把这个地方用map做了个缓存。这似乎不是最佳解决方法。期待你的解决方法:)
```
	private static HashMap<String, ZkManagerImpl> conn_cache = new HashMap<> ();

	public static ZkManagerImpl connect(String host, int timeout) {
		String key = host +"#"+ timeout;
		ZkManagerImpl zkimpl = conn_cache.get(key);
		if(zkimpl != null){
			return zkimpl;
		}
		try {
			zkimpl = ZkManagerImpl.createZk2();
			zkimpl.zkConnectInfo.setConnectStr(host);
			zkimpl.zkConnectInfo.setTimeout(timeout);
			zkimpl.zk = new ZooKeeper(host, timeout, zkimpl);
			conn_cache.put(key, zkimpl);
		} catch (Exception e) {
			e.printStackTrace();
			zkimpl = null;
		}
		return zkimpl;
	}
```

2.改进：建议不要用zk原生api，使用框架诸如curator等。

**Comment by zhaolun7** [comment]
页面无法保存数据
修改src\main\resources\templates\info.html  添加th开头
```
66:			    <input type="hidden" th:value="${cacheId}" name="cacheId" />
67:			    <input type="hidden" th:value="${path}" name="path" />
```

**Comment by zhitom** [comment]
多谢发现的bug：

1）修改如下，主要是在put前进行判断，否则进行reconnect，不再重新创建。
` ZkManager zkManager;

		for(Map<String , Object> m : ZkCfgFactory.createZkCfgManager().query()){

			zkManager=ZkCache.get(m.get("ID").toString());

			if(zkManager==null) {

				log.info("zk info: id={},connectstr={},timeout={}",m.get("ID"),m.get("CONNECTSTR"),m.get("SESSIONTIMEOUT"));

				ZkCache.put(m.get("ID").toString(), ZkManagerImpl.createZk().connect(m.get("CONNECTSTR").toString(), Integer.parseInt(m.get("SESSIONTIMEOUT").toString())));

			}else {

				log.info("zk(exists) info: id={},connectstr={},timeout={}",m.get("ID"),m.get("CONNECTSTR"),m.get("SESSIONTIMEOUT"));

				zkManager.reconnect();

			}

		}`
2）已经插入th
`
 &lt;input type="hidden" th:value="${cacheId}" name="cacheId" /&gt;

 &lt;input type="hidden" th:value="${path}" name="path" /&gt;
`

3）非常好的建议，因为是在别人的基础之上修改的，当时出于时间的关系，还未来得及使用curator改造，等后续后时间时进行改造。这里，也欢迎大家修改提交，一起完善该监控
