### ISSUE TITLE
关于zkweb项目 maven打包成war包，部署到tomcat上问题

### ISSUE THREAD

**Issue by wmsJackWang** [zhitom/zkweb#6]
作者您好，看你的博客 然后使用你的这个zookeeper  web管理工具，我是用jekins使用maven打包工具，打包发布到tomcat的包下，运行无法访问到你得项目，但我看你的pom文件和启动类已经做了tomcat部署支持改动，但是还是无法访问，能补充个个详细的war打包并运行在tomcat中的过程吗？谢谢！！感谢！
联系邮箱 : mingshengwang@sohu-inc.com
name：jackdking

**Comment by zhitom** [comment]
您好,
  如您所说,有两个pom,一个用于生成jar,直接可以按普通应用模式运行;一个用于生成war,部署到tomcat或weblogic即可运行,tomcat和weblogic我们都做过部署测试,是可以部署访问的.
  另外,假设部署包名为zkWeb-v1.2.1.war,部署到tomcat的webapps/zkWeb-v1.2.1.war,tomcat会自动解压到目录webapps/zkWeb-v1.2.1,浏览器访问的地址为 http://yourip:yourport/zkWeb-v1.2.1,所以请注意部署的war包名.

请核晓试试看,谢谢!

**Comment by wmsJackWang** [comment]
![image](https://user-images.githubusercontent.com/19822486/62508235-79587e00-b839-11e9-9f05-5ce4ee66b5c8.png)
![image](https://user-images.githubusercontent.com/19822486/62508240-7c536e80-b839-11e9-93ab-b488f5a34cdf.png)
![image](https://user-images.githubusercontent.com/19822486/62508242-807f8c00-b839-11e9-96c4-f8dc5de83f37.png)
![image](https://user-images.githubusercontent.com/19822486/62508246-84aba980-b839-11e9-9ad2-00235202f9b3.png)
![image](https://user-images.githubusercontent.com/19822486/62508250-883f3080-b839-11e9-96f1-bcf35cb917d8.png)

您好，项目打包没问题，pom文件也是选择pom-tomcat , tomcat成功运行，但是项目不能访问，报了404，猜测是不是静态文件访问有问题呢？跟你pom文件 中的注释有关系吗？
  我在springboot项目的window和Linux环境中也遇到过静态资源访问问题。

本地启动springboot项目，运行成功！
![image](https://user-images.githubusercontent.com/19822486/62508374-e409b980-b839-11e9-99e9-47cc248bb99a.png)

**Comment by zhitom** [comment]
您好,我一般是将pom-tomcat.xml改名成pom.xml,避免pom文件名原因带来其他问题(将来可以考虑使用profile的方式实现打包).
如果是静态文件问题,可以按F12进入console查看错误信息,便可知晓.
祝好运!

另外,你可以试试手工部署(建议使用mv方式)war到tomcat/webapps试试,确保不是包的问题.

**Comment by zhitom** [comment]
您好,我刚才测试了一下,可能是加载时间有点长引起的误解,请核查tomcat的启动日志,在等待出现SPRING的文本字符串提示之后的一段时间才可以访问.

**Comment by wmsJackWang** [comment]
![image](https://user-images.githubusercontent.com/19822486/62819738-08dc9480-bb8c-11e9-82c2-a8a7bd9ce676.png)
您好，本地maven编译的war包放到webapps目录下启动 该项目报的错，我对h2不了解，连接没有获取到，导致整个项目没起来。我也是使用修改pom-tomcat名字为pom起的。

**Comment by wmsJackWang** [comment]
项目导入eclipse直接启动是能访问使用的，现在是我想把这个工具应用放到我服务器上，以后直接使用。谢谢

**Comment by wmsJackWang** [comment]
您好，如果您方便的话，咋们加个qq吧，1042164771，谢谢。

**Comment by wmsJackWang** [comment]
您好，已经解决！！！
分享下zkweb项目部署到centos7失败的解决路径
1.经过和作者交流，确定问题是tomcat启动时候项目时候，初始化的数据库连接connection未获取
     发现：h2数据库自动在window的.h2文件夹下创建了数据库，如下图：
![image](https://user-images.githubusercontent.com/19822486/63206762-16929c80-c0ed-11e9-9341-1d91cf42a96f.png)
      猜想：嵌入式h2的数据源的url错误，是否应该h2在linux系统中的路径需要修改。
      结果：还是失败，获取不到数据源
      本人不太了解h2，因此果断放弃这种h2需要很多学习成本的解决路径，选择mysql库，也方便以后二次开发时候权限管理模块的添加。

       使用mysql库后，发现问题还是没有解决，因此关注点不再是数据库问题，因该就能确定是datasource没有加载到bean容器中了，在搜索后发现，和WebMvcConfigurer一个继承体系的类WebMvcConfigurationSupport，继承这个类会使得配置失效，如下图所示：
![image](https://user-images.githubusercontent.com/19822486/63206888-bcdfa180-c0ef-11e9-8e49-621368f41e2d.png)
博文源地址：https://blog.csdn.net/fmwind/article/details/82832758
        至此只是我的猜想，可能是zkweb的自动配置类继承了WebMvcConfigurer导致配置类失效，进而使得datasource没有放入到bean容器当中，因此导致项目为获取connection。
         
        想到这，开始验证（：快速搭建起来这个zkweb管理工具，先成功，研究和二次开发工作以后再说，现在学习目标是熟练使用zookeeper体系，而不是这个工具，本着这个核心想法）
        讲WebMvcConfigurer和项目的配置类分割，如下图
![image](https://user-images.githubusercontent.com/19822486/63206919-4a22f600-c0f0-11e9-8c8f-33b3a6238a45.png)
![image](https://user-images.githubusercontent.com/19822486/63206923-55762180-c0f0-11e9-9b38-cdbcb3d9372d.png)
将ZkSpringBootConfiguration只作为自动配置类使用。

从新编译部署项目后，项目成功启动，catalina日志不再有错误日志，项目访问成功，如下图：
![Uploading image.png…]()
